# This is a basic workflow to help you get started with Actions

name: JDK JRE Benchmark

on:
  push:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 11, 17, 21]
        mode: [jdk, jre]

    steps:
    - name: Set up Java ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}
        java-package: ${{ matrix.mode }}