name: Check Java Version

on:
  push:
    branches:
      - main

jobs:
  check-java:
    runs-on: ubuntu-latest
    steps:
      - name: Check Java Version
        run: |
          javac -version
          java -version
        
      - name: List Installed Java Versions
        run: |
          sudo update-java-alternatives --list

      - name: Check JAVA_HOME
        run: echo $JAVA_HOME

