name: benchmark-java

permissions:
  contents: read

on:
  push:
    branches:
      - 'main'

jobs:
  benchmark:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        case:
          - openjdk:17
          - openjdk:17-jdk-slim
          - openjdk:17-jdk-alpine
          - eclipse-temurin:17
          - eclipse-temurin:17-jdk-alpine
          - eclipse-temurin:17-jre
          - eclipse-temurin:17-jre-alpine
          - amazoncorretto:17
          - amazoncorretto:17-alpine
          - bellsoft/liberica-openjdk-debian:17
          - bellsoft/liberica-openjre-debian:17
          - bellsoft/liberica-openjdk-alpine:17
          - bellsoft/liberica-openjre-alpine:17

    steps:
      - name: Checkout code
        run: |
          git clone https://github.com/Juser0/military-recruit.git

      - name: Get commit count
        run: |
          cd military-recruit
          echo "count=$(git rev-list --all --count)" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: |
          cd military-recruit
          chmod +x gradlew

      - name: Build application (if Dockerfile case)
        if: matrix.case != 'bootBuildImage'
        run: |
          cd military-recruit
          ./gradlew build -x test

      - name: Generate Dockerfile (if Dockerfile case)
        if: matrix.case != 'bootBuildImage'
        run: |
          cd military-recruit
          case="${{ matrix.case }}"
          echo "FROM $case" > Dockerfile
          echo "COPY build/libs/*.jar /app/app.jar" >> Dockerfile
          echo "WORKDIR /app" >> Dockerfile
          echo "CMD [\"java\", \"-jar\", \"app.jar\"]" >> Dockerfile

      - name: Build Docker image (if Dockerfile case)
        run: |
          cd military-recruit
          docker build -t dockerfile:${{ env.count }} .

      - name: Save Docker image as tar (if Dockerfile case)
        run: |
            echo "VALID_CASE_NAME=${{ matrix.case }}-${{ env.count }}" | sed 's/:/_/g' >> $GITHUB_ENV
            cd military-recruit
            docker save dockerfile:${{ env.count }} -o dockerfiles.tar

      - name: Upload Docker image artifact (if Dockerfile case)
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.VALID_CASE_NAME }}
          path: ./military-recruit/dockerfiles.tar
