name: Manually Run Test

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - 'test'
  workflow_dispatch:

jobs:
  test-work:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Get Commit count
        run: echo "count=$(git rev-list --all --count)"